export type Screen =
  | "setup"
  | "password-setup"
  | "import"
  | "generated"
  | "wallet"
  | "send"
  | "send-erc20"
  | "unlock"
  | "view-private-key"
  | "multisig"
  | "multisig-interact"
  | "tokens"
  | "address-book"
  | "sign-out"
  | "transaction-success"
  | "multisig-deployment-success"
  | "multisig-transaction-success";
